### ISSUE TITLE
[SUGGESTION] Redstone powered!

### ISSUE THREAD

**Issue by MarkinhosMLP** [PQguanfang/MythicTotem#3]
So... i want to make a Copper golem, but i wanted the condition to be... powered by a button/lever
imagine how may things could be done with this ????? imagine a frankestein golem for example

so, the suggestion is, you build the totem, but you have to activate it with a button/lever/redstone block, then it would drop or break the button/lever/block and summon the golem

for example

'DCD'     A= copper block      B= carved pumpkin 
 DBD'     C = lightning rod    D= none
'DAD'

conditions:
- 'redstone'

**Comment by PQguanfang** [comment]
The feature you propose cannot be implemented anytime soon, because in SpigotAPI, a redstone signal is not related to a player, which results in that although the plugin accepts a redstone signal, there is no way to know exactly which player activated it.
